/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.pojos;


import com.rbkmoney.reporter.domain.enums.ReportType;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractMeta implements Serializable {

    private static final long serialVersionUID = 461645780;

    private String        partyId;
    private String        contractId;
    private ReportType    reportType;
    private LocalDateTime wtime;
    private Long          lastEventId;
    private Integer       scheduleId;
    private Integer       calendarId;
    private LocalDateTime lastReportCreatedAt;
    private Long          lastClosingBalance;
    private String        representativePosition;
    private String        representativeFullName;
    private String        representativeDocument;
    private String        legalAgreementId;
    private LocalDateTime legalAgreementSignedAt;
    private LocalDateTime legalAgreementValidUntil;

    public ContractMeta() {}

    public ContractMeta(ContractMeta value) {
        this.partyId = value.partyId;
        this.contractId = value.contractId;
        this.reportType = value.reportType;
        this.wtime = value.wtime;
        this.lastEventId = value.lastEventId;
        this.scheduleId = value.scheduleId;
        this.calendarId = value.calendarId;
        this.lastReportCreatedAt = value.lastReportCreatedAt;
        this.lastClosingBalance = value.lastClosingBalance;
        this.representativePosition = value.representativePosition;
        this.representativeFullName = value.representativeFullName;
        this.representativeDocument = value.representativeDocument;
        this.legalAgreementId = value.legalAgreementId;
        this.legalAgreementSignedAt = value.legalAgreementSignedAt;
        this.legalAgreementValidUntil = value.legalAgreementValidUntil;
    }

    public ContractMeta(
        String        partyId,
        String        contractId,
        ReportType    reportType,
        LocalDateTime wtime,
        Long          lastEventId,
        Integer       scheduleId,
        Integer       calendarId,
        LocalDateTime lastReportCreatedAt,
        Long          lastClosingBalance,
        String        representativePosition,
        String        representativeFullName,
        String        representativeDocument,
        String        legalAgreementId,
        LocalDateTime legalAgreementSignedAt,
        LocalDateTime legalAgreementValidUntil
    ) {
        this.partyId = partyId;
        this.contractId = contractId;
        this.reportType = reportType;
        this.wtime = wtime;
        this.lastEventId = lastEventId;
        this.scheduleId = scheduleId;
        this.calendarId = calendarId;
        this.lastReportCreatedAt = lastReportCreatedAt;
        this.lastClosingBalance = lastClosingBalance;
        this.representativePosition = representativePosition;
        this.representativeFullName = representativeFullName;
        this.representativeDocument = representativeDocument;
        this.legalAgreementId = legalAgreementId;
        this.legalAgreementSignedAt = legalAgreementSignedAt;
        this.legalAgreementValidUntil = legalAgreementValidUntil;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getContractId() {
        return this.contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public ReportType getReportType() {
        return this.reportType;
    }

    public void setReportType(ReportType reportType) {
        this.reportType = reportType;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    public Long getLastEventId() {
        return this.lastEventId;
    }

    public void setLastEventId(Long lastEventId) {
        this.lastEventId = lastEventId;
    }

    public Integer getScheduleId() {
        return this.scheduleId;
    }

    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    public Integer getCalendarId() {
        return this.calendarId;
    }

    public void setCalendarId(Integer calendarId) {
        this.calendarId = calendarId;
    }

    public LocalDateTime getLastReportCreatedAt() {
        return this.lastReportCreatedAt;
    }

    public void setLastReportCreatedAt(LocalDateTime lastReportCreatedAt) {
        this.lastReportCreatedAt = lastReportCreatedAt;
    }

    public Long getLastClosingBalance() {
        return this.lastClosingBalance;
    }

    public void setLastClosingBalance(Long lastClosingBalance) {
        this.lastClosingBalance = lastClosingBalance;
    }

    public String getRepresentativePosition() {
        return this.representativePosition;
    }

    public void setRepresentativePosition(String representativePosition) {
        this.representativePosition = representativePosition;
    }

    public String getRepresentativeFullName() {
        return this.representativeFullName;
    }

    public void setRepresentativeFullName(String representativeFullName) {
        this.representativeFullName = representativeFullName;
    }

    public String getRepresentativeDocument() {
        return this.representativeDocument;
    }

    public void setRepresentativeDocument(String representativeDocument) {
        this.representativeDocument = representativeDocument;
    }

    public String getLegalAgreementId() {
        return this.legalAgreementId;
    }

    public void setLegalAgreementId(String legalAgreementId) {
        this.legalAgreementId = legalAgreementId;
    }

    public LocalDateTime getLegalAgreementSignedAt() {
        return this.legalAgreementSignedAt;
    }

    public void setLegalAgreementSignedAt(LocalDateTime legalAgreementSignedAt) {
        this.legalAgreementSignedAt = legalAgreementSignedAt;
    }

    public LocalDateTime getLegalAgreementValidUntil() {
        return this.legalAgreementValidUntil;
    }

    public void setLegalAgreementValidUntil(LocalDateTime legalAgreementValidUntil) {
        this.legalAgreementValidUntil = legalAgreementValidUntil;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ContractMeta other = (ContractMeta) obj;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (contractId == null) {
            if (other.contractId != null)
                return false;
        }
        else if (!contractId.equals(other.contractId))
            return false;
        if (reportType == null) {
            if (other.reportType != null)
                return false;
        }
        else if (!reportType.equals(other.reportType))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        if (lastEventId == null) {
            if (other.lastEventId != null)
                return false;
        }
        else if (!lastEventId.equals(other.lastEventId))
            return false;
        if (scheduleId == null) {
            if (other.scheduleId != null)
                return false;
        }
        else if (!scheduleId.equals(other.scheduleId))
            return false;
        if (calendarId == null) {
            if (other.calendarId != null)
                return false;
        }
        else if (!calendarId.equals(other.calendarId))
            return false;
        if (lastReportCreatedAt == null) {
            if (other.lastReportCreatedAt != null)
                return false;
        }
        else if (!lastReportCreatedAt.equals(other.lastReportCreatedAt))
            return false;
        if (lastClosingBalance == null) {
            if (other.lastClosingBalance != null)
                return false;
        }
        else if (!lastClosingBalance.equals(other.lastClosingBalance))
            return false;
        if (representativePosition == null) {
            if (other.representativePosition != null)
                return false;
        }
        else if (!representativePosition.equals(other.representativePosition))
            return false;
        if (representativeFullName == null) {
            if (other.representativeFullName != null)
                return false;
        }
        else if (!representativeFullName.equals(other.representativeFullName))
            return false;
        if (representativeDocument == null) {
            if (other.representativeDocument != null)
                return false;
        }
        else if (!representativeDocument.equals(other.representativeDocument))
            return false;
        if (legalAgreementId == null) {
            if (other.legalAgreementId != null)
                return false;
        }
        else if (!legalAgreementId.equals(other.legalAgreementId))
            return false;
        if (legalAgreementSignedAt == null) {
            if (other.legalAgreementSignedAt != null)
                return false;
        }
        else if (!legalAgreementSignedAt.equals(other.legalAgreementSignedAt))
            return false;
        if (legalAgreementValidUntil == null) {
            if (other.legalAgreementValidUntil != null)
                return false;
        }
        else if (!legalAgreementValidUntil.equals(other.legalAgreementValidUntil))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.contractId == null) ? 0 : this.contractId.hashCode());
        result = prime * result + ((this.reportType == null) ? 0 : this.reportType.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        result = prime * result + ((this.lastEventId == null) ? 0 : this.lastEventId.hashCode());
        result = prime * result + ((this.scheduleId == null) ? 0 : this.scheduleId.hashCode());
        result = prime * result + ((this.calendarId == null) ? 0 : this.calendarId.hashCode());
        result = prime * result + ((this.lastReportCreatedAt == null) ? 0 : this.lastReportCreatedAt.hashCode());
        result = prime * result + ((this.lastClosingBalance == null) ? 0 : this.lastClosingBalance.hashCode());
        result = prime * result + ((this.representativePosition == null) ? 0 : this.representativePosition.hashCode());
        result = prime * result + ((this.representativeFullName == null) ? 0 : this.representativeFullName.hashCode());
        result = prime * result + ((this.representativeDocument == null) ? 0 : this.representativeDocument.hashCode());
        result = prime * result + ((this.legalAgreementId == null) ? 0 : this.legalAgreementId.hashCode());
        result = prime * result + ((this.legalAgreementSignedAt == null) ? 0 : this.legalAgreementSignedAt.hashCode());
        result = prime * result + ((this.legalAgreementValidUntil == null) ? 0 : this.legalAgreementValidUntil.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractMeta (");

        sb.append(partyId);
        sb.append(", ").append(contractId);
        sb.append(", ").append(reportType);
        sb.append(", ").append(wtime);
        sb.append(", ").append(lastEventId);
        sb.append(", ").append(scheduleId);
        sb.append(", ").append(calendarId);
        sb.append(", ").append(lastReportCreatedAt);
        sb.append(", ").append(lastClosingBalance);
        sb.append(", ").append(representativePosition);
        sb.append(", ").append(representativeFullName);
        sb.append(", ").append(representativeDocument);
        sb.append(", ").append(legalAgreementId);
        sb.append(", ").append(legalAgreementSignedAt);
        sb.append(", ").append(legalAgreementValidUntil);

        sb.append(")");
        return sb.toString();
    }
}
