/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileMeta implements Serializable {

    private static final long serialVersionUID = -2043244136;

    private String fileId;
    private String bucketId;
    private Long   reportId;
    private String filename;
    private String md5;
    private String sha256;

    public FileMeta() {}

    public FileMeta(FileMeta value) {
        this.fileId = value.fileId;
        this.bucketId = value.bucketId;
        this.reportId = value.reportId;
        this.filename = value.filename;
        this.md5 = value.md5;
        this.sha256 = value.sha256;
    }

    public FileMeta(
        String fileId,
        String bucketId,
        Long   reportId,
        String filename,
        String md5,
        String sha256
    ) {
        this.fileId = fileId;
        this.bucketId = bucketId;
        this.reportId = reportId;
        this.filename = filename;
        this.md5 = md5;
        this.sha256 = sha256;
    }

    public String getFileId() {
        return this.fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getBucketId() {
        return this.bucketId;
    }

    public void setBucketId(String bucketId) {
        this.bucketId = bucketId;
    }

    public Long getReportId() {
        return this.reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getMd5() {
        return this.md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getSha256() {
        return this.sha256;
    }

    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FileMeta other = (FileMeta) obj;
        if (fileId == null) {
            if (other.fileId != null)
                return false;
        }
        else if (!fileId.equals(other.fileId))
            return false;
        if (bucketId == null) {
            if (other.bucketId != null)
                return false;
        }
        else if (!bucketId.equals(other.bucketId))
            return false;
        if (reportId == null) {
            if (other.reportId != null)
                return false;
        }
        else if (!reportId.equals(other.reportId))
            return false;
        if (filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!filename.equals(other.filename))
            return false;
        if (md5 == null) {
            if (other.md5 != null)
                return false;
        }
        else if (!md5.equals(other.md5))
            return false;
        if (sha256 == null) {
            if (other.sha256 != null)
                return false;
        }
        else if (!sha256.equals(other.sha256))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((fileId == null) ? 0 : fileId.hashCode());
        result = prime * result + ((bucketId == null) ? 0 : bucketId.hashCode());
        result = prime * result + ((reportId == null) ? 0 : reportId.hashCode());
        result = prime * result + ((filename == null) ? 0 : filename.hashCode());
        result = prime * result + ((md5 == null) ? 0 : md5.hashCode());
        result = prime * result + ((sha256 == null) ? 0 : sha256.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileMeta (");

        sb.append(fileId);
        sb.append(", ").append(bucketId);
        sb.append(", ").append(reportId);
        sb.append(", ").append(filename);
        sb.append(", ").append(md5);
        sb.append(", ").append(sha256);

        sb.append(")");
        return sb.toString();
    }
}
