/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosReportMeta implements Serializable {

    private static final long serialVersionUID = 1640003159;

    private String        partyId;
    private String        contractId;
    private Long          lastOpeningBalance;
    private Long          lastClosingBalance;
    private LocalDateTime lastReportCreatedAt;

    public PosReportMeta() {}

    public PosReportMeta(PosReportMeta value) {
        this.partyId = value.partyId;
        this.contractId = value.contractId;
        this.lastOpeningBalance = value.lastOpeningBalance;
        this.lastClosingBalance = value.lastClosingBalance;
        this.lastReportCreatedAt = value.lastReportCreatedAt;
    }

    public PosReportMeta(
        String        partyId,
        String        contractId,
        Long          lastOpeningBalance,
        Long          lastClosingBalance,
        LocalDateTime lastReportCreatedAt
    ) {
        this.partyId = partyId;
        this.contractId = contractId;
        this.lastOpeningBalance = lastOpeningBalance;
        this.lastClosingBalance = lastClosingBalance;
        this.lastReportCreatedAt = lastReportCreatedAt;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getContractId() {
        return this.contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public Long getLastOpeningBalance() {
        return this.lastOpeningBalance;
    }

    public void setLastOpeningBalance(Long lastOpeningBalance) {
        this.lastOpeningBalance = lastOpeningBalance;
    }

    public Long getLastClosingBalance() {
        return this.lastClosingBalance;
    }

    public void setLastClosingBalance(Long lastClosingBalance) {
        this.lastClosingBalance = lastClosingBalance;
    }

    public LocalDateTime getLastReportCreatedAt() {
        return this.lastReportCreatedAt;
    }

    public void setLastReportCreatedAt(LocalDateTime lastReportCreatedAt) {
        this.lastReportCreatedAt = lastReportCreatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PosReportMeta other = (PosReportMeta) obj;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (contractId == null) {
            if (other.contractId != null)
                return false;
        }
        else if (!contractId.equals(other.contractId))
            return false;
        if (lastOpeningBalance == null) {
            if (other.lastOpeningBalance != null)
                return false;
        }
        else if (!lastOpeningBalance.equals(other.lastOpeningBalance))
            return false;
        if (lastClosingBalance == null) {
            if (other.lastClosingBalance != null)
                return false;
        }
        else if (!lastClosingBalance.equals(other.lastClosingBalance))
            return false;
        if (lastReportCreatedAt == null) {
            if (other.lastReportCreatedAt != null)
                return false;
        }
        else if (!lastReportCreatedAt.equals(other.lastReportCreatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.contractId == null) ? 0 : this.contractId.hashCode());
        result = prime * result + ((this.lastOpeningBalance == null) ? 0 : this.lastOpeningBalance.hashCode());
        result = prime * result + ((this.lastClosingBalance == null) ? 0 : this.lastClosingBalance.hashCode());
        result = prime * result + ((this.lastReportCreatedAt == null) ? 0 : this.lastReportCreatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PosReportMeta (");

        sb.append(partyId);
        sb.append(", ").append(contractId);
        sb.append(", ").append(lastOpeningBalance);
        sb.append(", ").append(lastClosingBalance);
        sb.append(", ").append(lastReportCreatedAt);

        sb.append(")");
        return sb.toString();
    }
}
