/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables;


import com.rbkmoney.reporter.domain.Keys;
import com.rbkmoney.reporter.domain.Rpt;
import com.rbkmoney.reporter.domain.tables.records.ContractMetaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractMeta extends TableImpl<ContractMetaRecord> {

    private static final long serialVersionUID = -1451505989;

    /**
     * The reference instance of <code>rpt.contract_meta</code>
     */
    public static final ContractMeta CONTRACT_META = new ContractMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractMetaRecord> getRecordType() {
        return ContractMetaRecord.class;
    }

    /**
     * The column <code>rpt.contract_meta.party_id</code>.
     */
    public final TableField<ContractMetaRecord, String> PARTY_ID = createField("party_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.contract_meta.contract_id</code>.
     */
    public final TableField<ContractMetaRecord, String> CONTRACT_ID = createField("contract_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.contract_meta.wtime</code>.
     */
    public final TableField<ContractMetaRecord, LocalDateTime> WTIME = createField("wtime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>rpt.contract_meta.last_event_id</code>.
     */
    public final TableField<ContractMetaRecord, Long> LAST_EVENT_ID = createField("last_event_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rpt.contract_meta.schedule_id</code>.
     */
    public final TableField<ContractMetaRecord, Integer> SCHEDULE_ID = createField("schedule_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rpt.contract_meta.calendar_id</code>.
     */
    public final TableField<ContractMetaRecord, Integer> CALENDAR_ID = createField("calendar_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rpt.contract_meta.last_report_created_at</code>.
     */
    public final TableField<ContractMetaRecord, LocalDateTime> LAST_REPORT_CREATED_AT = createField("last_report_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>rpt.contract_meta.last_closing_balance</code>.
     */
    public final TableField<ContractMetaRecord, Long> LAST_CLOSING_BALANCE = createField("last_closing_balance", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>rpt.contract_meta.representative_position</code>.
     */
    public final TableField<ContractMetaRecord, String> REPRESENTATIVE_POSITION = createField("representative_position", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rpt.contract_meta.representative_full_name</code>.
     */
    public final TableField<ContractMetaRecord, String> REPRESENTATIVE_FULL_NAME = createField("representative_full_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rpt.contract_meta.representative_document</code>.
     */
    public final TableField<ContractMetaRecord, String> REPRESENTATIVE_DOCUMENT = createField("representative_document", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rpt.contract_meta.legal_agreement_id</code>.
     */
    public final TableField<ContractMetaRecord, String> LEGAL_AGREEMENT_ID = createField("legal_agreement_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rpt.contract_meta.legal_agreement_signed_at</code>.
     */
    public final TableField<ContractMetaRecord, LocalDateTime> LEGAL_AGREEMENT_SIGNED_AT = createField("legal_agreement_signed_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>rpt.contract_meta.legal_agreement_valid_until</code>.
     */
    public final TableField<ContractMetaRecord, LocalDateTime> LEGAL_AGREEMENT_VALID_UNTIL = createField("legal_agreement_valid_until", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>rpt.contract_meta</code> table reference
     */
    public ContractMeta() {
        this("contract_meta", null);
    }

    /**
     * Create an aliased <code>rpt.contract_meta</code> table reference
     */
    public ContractMeta(String alias) {
        this(alias, CONTRACT_META);
    }

    private ContractMeta(String alias, Table<ContractMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractMeta(String alias, Table<ContractMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpt.RPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractMetaRecord> getPrimaryKey() {
        return Keys.CONTRACT_META_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractMetaRecord>>asList(Keys.CONTRACT_META_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMeta as(String alias) {
        return new ContractMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractMeta rename(String name) {
        return new ContractMeta(name, null);
    }
}
