/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables;


import com.rbkmoney.reporter.domain.Keys;
import com.rbkmoney.reporter.domain.Rpt;
import com.rbkmoney.reporter.domain.tables.records.FileMetaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileMeta extends TableImpl<FileMetaRecord> {

    private static final long serialVersionUID = 545391216;

    /**
     * The reference instance of <code>rpt.file_meta</code>
     */
    public static final FileMeta FILE_META = new FileMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileMetaRecord> getRecordType() {
        return FileMetaRecord.class;
    }

    /**
     * The column <code>rpt.file_meta.file_id</code>.
     */
    public final TableField<FileMetaRecord, String> FILE_ID = createField("file_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file_meta.bucket_id</code>.
     */
    public final TableField<FileMetaRecord, String> BUCKET_ID = createField("bucket_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file_meta.report_id</code>.
     */
    public final TableField<FileMetaRecord, Long> REPORT_ID = createField("report_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rpt.file_meta.filename</code>.
     */
    public final TableField<FileMetaRecord, String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file_meta.md5</code>.
     */
    public final TableField<FileMetaRecord, String> MD5 = createField("md5", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file_meta.sha256</code>.
     */
    public final TableField<FileMetaRecord, String> SHA256 = createField("sha256", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>rpt.file_meta</code> table reference
     */
    public FileMeta() {
        this("file_meta", null);
    }

    /**
     * Create an aliased <code>rpt.file_meta</code> table reference
     */
    public FileMeta(String alias) {
        this(alias, FILE_META);
    }

    private FileMeta(String alias, Table<FileMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileMeta(String alias, Table<FileMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpt.RPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FileMetaRecord> getPrimaryKey() {
        return Keys.FILE_META_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FileMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<FileMetaRecord>>asList(Keys.FILE_META_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMeta as(String alias) {
        return new FileMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileMeta rename(String name) {
        return new FileMeta(name, null);
    }
}
