/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables;


import com.rbkmoney.reporter.domain.Keys;
import com.rbkmoney.reporter.domain.Rpt;
import com.rbkmoney.reporter.domain.tables.records.PosReportMetaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosReportMeta extends TableImpl<PosReportMetaRecord> {

    private static final long serialVersionUID = 1358879053;

    /**
     * The reference instance of <code>rpt.pos_report_meta</code>
     */
    public static final PosReportMeta POS_REPORT_META = new PosReportMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PosReportMetaRecord> getRecordType() {
        return PosReportMetaRecord.class;
    }

    /**
     * The column <code>rpt.pos_report_meta.party_id</code>.
     */
    public final TableField<PosReportMetaRecord, String> PARTY_ID = createField("party_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.pos_report_meta.contract_id</code>.
     */
    public final TableField<PosReportMetaRecord, String> CONTRACT_ID = createField("contract_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.pos_report_meta.last_opening_balance</code>.
     */
    public final TableField<PosReportMetaRecord, Long> LAST_OPENING_BALANCE = createField("last_opening_balance", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>rpt.pos_report_meta.last_closing_balance</code>.
     */
    public final TableField<PosReportMetaRecord, Long> LAST_CLOSING_BALANCE = createField("last_closing_balance", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>rpt.pos_report_meta.last_report_created_at</code>.
     */
    public final TableField<PosReportMetaRecord, LocalDateTime> LAST_REPORT_CREATED_AT = createField("last_report_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>rpt.pos_report_meta</code> table reference
     */
    public PosReportMeta() {
        this("pos_report_meta", null);
    }

    /**
     * Create an aliased <code>rpt.pos_report_meta</code> table reference
     */
    public PosReportMeta(String alias) {
        this(alias, POS_REPORT_META);
    }

    private PosReportMeta(String alias, Table<PosReportMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private PosReportMeta(String alias, Table<PosReportMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpt.RPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PosReportMetaRecord> getPrimaryKey() {
        return Keys.POS_REPORT_META_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PosReportMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<PosReportMetaRecord>>asList(Keys.POS_REPORT_META_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PosReportMeta as(String alias) {
        return new PosReportMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PosReportMeta rename(String name) {
        return new PosReportMeta(name, null);
    }
}
