/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in rpt
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>rpt.report_id_seq</code>
     */
    public static final Sequence<Long> REPORT_ID_SEQ = new SequenceImpl<Long>("report_id_seq", Rpt.RPT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
