/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.records;


import com.rbkmoney.reporter.domain.enums.ReportType;
import com.rbkmoney.reporter.domain.tables.ContractMeta;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record3;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractMetaRecord extends UpdatableRecordImpl<ContractMetaRecord> implements Record15<String, String, ReportType, LocalDateTime, Long, Integer, Integer, LocalDateTime, Long, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 451088723;

    /**
     * Setter for <code>rpt.contract_meta.party_id</code>.
     */
    public void setPartyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>rpt.contract_meta.contract_id</code>.
     */
    public void setContractId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.contract_id</code>.
     */
    public String getContractId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rpt.contract_meta.report_type</code>.
     */
    public void setReportType(ReportType value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.report_type</code>.
     */
    public ReportType getReportType() {
        return (ReportType) get(2);
    }

    /**
     * Setter for <code>rpt.contract_meta.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>rpt.contract_meta.last_event_id</code>.
     */
    public void setLastEventId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.last_event_id</code>.
     */
    public Long getLastEventId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>rpt.contract_meta.schedule_id</code>.
     */
    public void setScheduleId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.schedule_id</code>.
     */
    public Integer getScheduleId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>rpt.contract_meta.calendar_id</code>.
     */
    public void setCalendarId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.calendar_id</code>.
     */
    public Integer getCalendarId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>rpt.contract_meta.last_report_created_at</code>.
     */
    public void setLastReportCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.last_report_created_at</code>.
     */
    public LocalDateTime getLastReportCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>rpt.contract_meta.last_closing_balance</code>.
     */
    public void setLastClosingBalance(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.last_closing_balance</code>.
     */
    public Long getLastClosingBalance() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>rpt.contract_meta.representative_position</code>.
     */
    public void setRepresentativePosition(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.representative_position</code>.
     */
    public String getRepresentativePosition() {
        return (String) get(9);
    }

    /**
     * Setter for <code>rpt.contract_meta.representative_full_name</code>.
     */
    public void setRepresentativeFullName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.representative_full_name</code>.
     */
    public String getRepresentativeFullName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>rpt.contract_meta.representative_document</code>.
     */
    public void setRepresentativeDocument(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.representative_document</code>.
     */
    public String getRepresentativeDocument() {
        return (String) get(11);
    }

    /**
     * Setter for <code>rpt.contract_meta.legal_agreement_id</code>.
     */
    public void setLegalAgreementId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.legal_agreement_id</code>.
     */
    public String getLegalAgreementId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>rpt.contract_meta.legal_agreement_signed_at</code>.
     */
    public void setLegalAgreementSignedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.legal_agreement_signed_at</code>.
     */
    public LocalDateTime getLegalAgreementSignedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>rpt.contract_meta.legal_agreement_valid_until</code>.
     */
    public void setLegalAgreementValidUntil(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.legal_agreement_valid_until</code>.
     */
    public LocalDateTime getLegalAgreementValidUntil() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, ReportType> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, ReportType, LocalDateTime, Long, Integer, Integer, LocalDateTime, Long, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, ReportType, LocalDateTime, Long, Integer, Integer, LocalDateTime, Long, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ContractMeta.CONTRACT_META.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContractMeta.CONTRACT_META.CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ReportType> field3() {
        return ContractMeta.CONTRACT_META.REPORT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return ContractMeta.CONTRACT_META.WTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ContractMeta.CONTRACT_META.LAST_EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ContractMeta.CONTRACT_META.SCHEDULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ContractMeta.CONTRACT_META.CALENDAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return ContractMeta.CONTRACT_META.LAST_REPORT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return ContractMeta.CONTRACT_META.LAST_CLOSING_BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ContractMeta.CONTRACT_META.REPRESENTATIVE_POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ContractMeta.CONTRACT_META.REPRESENTATIVE_FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ContractMeta.CONTRACT_META.REPRESENTATIVE_DOCUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return ContractMeta.CONTRACT_META.LEGAL_AGREEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return ContractMeta.CONTRACT_META.LEGAL_AGREEMENT_SIGNED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return ContractMeta.CONTRACT_META.LEGAL_AGREEMENT_VALID_UNTIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReportType value3() {
        return getReportType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getWtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLastEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCalendarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getLastReportCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getLastClosingBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRepresentativePosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRepresentativeFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRepresentativeDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLegalAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getLegalAgreementSignedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getLegalAgreementValidUntil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value1(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value2(String value) {
        setContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value3(ReportType value) {
        setReportType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value4(LocalDateTime value) {
        setWtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value5(Long value) {
        setLastEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value6(Integer value) {
        setScheduleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value7(Integer value) {
        setCalendarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value8(LocalDateTime value) {
        setLastReportCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value9(Long value) {
        setLastClosingBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value10(String value) {
        setRepresentativePosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value11(String value) {
        setRepresentativeFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value12(String value) {
        setRepresentativeDocument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value13(String value) {
        setLegalAgreementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value14(LocalDateTime value) {
        setLegalAgreementSignedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value15(LocalDateTime value) {
        setLegalAgreementValidUntil(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord values(String value1, String value2, ReportType value3, LocalDateTime value4, Long value5, Integer value6, Integer value7, LocalDateTime value8, Long value9, String value10, String value11, String value12, String value13, LocalDateTime value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractMetaRecord
     */
    public ContractMetaRecord() {
        super(ContractMeta.CONTRACT_META);
    }

    /**
     * Create a detached, initialised ContractMetaRecord
     */
    public ContractMetaRecord(String partyId, String contractId, ReportType reportType, LocalDateTime wtime, Long lastEventId, Integer scheduleId, Integer calendarId, LocalDateTime lastReportCreatedAt, Long lastClosingBalance, String representativePosition, String representativeFullName, String representativeDocument, String legalAgreementId, LocalDateTime legalAgreementSignedAt, LocalDateTime legalAgreementValidUntil) {
        super(ContractMeta.CONTRACT_META);

        set(0, partyId);
        set(1, contractId);
        set(2, reportType);
        set(3, wtime);
        set(4, lastEventId);
        set(5, scheduleId);
        set(6, calendarId);
        set(7, lastReportCreatedAt);
        set(8, lastClosingBalance);
        set(9, representativePosition);
        set(10, representativeFullName);
        set(11, representativeDocument);
        set(12, legalAgreementId);
        set(13, legalAgreementSignedAt);
        set(14, legalAgreementValidUntil);
    }
}
