/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.records;


import com.rbkmoney.reporter.domain.tables.FileMeta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileMetaRecord extends UpdatableRecordImpl<FileMetaRecord> implements Record6<String, String, Long, String, String, String> {

    private static final long serialVersionUID = 927732940;

    /**
     * Setter for <code>rpt.file_meta.file_id</code>.
     */
    public void setFileId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpt.file_meta.file_id</code>.
     */
    public String getFileId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>rpt.file_meta.bucket_id</code>.
     */
    public void setBucketId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpt.file_meta.bucket_id</code>.
     */
    public String getBucketId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rpt.file_meta.report_id</code>.
     */
    public void setReportId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpt.file_meta.report_id</code>.
     */
    public Long getReportId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>rpt.file_meta.filename</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpt.file_meta.filename</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rpt.file_meta.md5</code>.
     */
    public void setMd5(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rpt.file_meta.md5</code>.
     */
    public String getMd5() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rpt.file_meta.sha256</code>.
     */
    public void setSha256(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rpt.file_meta.sha256</code>.
     */
    public String getSha256() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Long, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Long, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return FileMeta.FILE_META.FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FileMeta.FILE_META.BUCKET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return FileMeta.FILE_META.REPORT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FileMeta.FILE_META.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FileMeta.FILE_META.MD5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FileMeta.FILE_META.SHA256;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBucketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMd5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSha256();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord value1(String value) {
        setFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord value2(String value) {
        setBucketId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord value3(Long value) {
        setReportId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord value4(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord value5(String value) {
        setMd5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord value6(String value) {
        setSha256(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileMetaRecord values(String value1, String value2, Long value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileMetaRecord
     */
    public FileMetaRecord() {
        super(FileMeta.FILE_META);
    }

    /**
     * Create a detached, initialised FileMetaRecord
     */
    public FileMetaRecord(String fileId, String bucketId, Long reportId, String filename, String md5, String sha256) {
        super(FileMeta.FILE_META);

        set(0, fileId);
        set(1, bucketId);
        set(2, reportId);
        set(3, filename);
        set(4, md5);
        set(5, sha256);
    }
}
